window.esdocSearchIndex = [
  [
    "time-functions/src/constants.js~hours_in_one_day",
    "variable/index.html#static-variable-HOURS_IN_ONE_DAY",
    "<span>HOURS_IN_ONE_DAY</span> <span class=\"search-result-import-path\">time-functions/src/constants.js</span>",
    "variable"
  ],
  [
    "time-functions/src/constants.js~milliseconds_in_one_second",
    "variable/index.html#static-variable-MILLISECONDS_IN_ONE_SECOND",
    "<span>MILLISECONDS_IN_ONE_SECOND</span> <span class=\"search-result-import-path\">time-functions/src/constants.js</span>",
    "variable"
  ],
  [
    "time-functions/src/constants.js~minutes_in_one_hour",
    "variable/index.html#static-variable-MINUTES_IN_ONE_HOUR",
    "<span>MINUTES_IN_ONE_HOUR</span> <span class=\"search-result-import-path\">time-functions/src/constants.js</span>",
    "variable"
  ],
  [
    "time-functions/src/constants.js~seconds_in_one_minute",
    "variable/index.html#static-variable-SECONDS_IN_ONE_MINUTE",
    "<span>SECONDS_IN_ONE_MINUTE</span> <span class=\"search-result-import-path\">time-functions/src/constants.js</span>",
    "variable"
  ],
  [
    "time-functions/src/hourstominutes.js~hourstominutes",
    "function/index.html#static-function-hoursToMinutes",
    "<span>hoursToMinutes</span> <span class=\"search-result-import-path\">time-functions/src/hoursToMinutes.js</span>",
    "function"
  ],
  [
    "time-functions/src/millisecondstoseconds.js~millisecondstoseconds",
    "function/index.html#static-function-millisecondsToSeconds",
    "<span>millisecondsToSeconds</span> <span class=\"search-result-import-path\">time-functions/src/millisecondsToSeconds.js</span>",
    "function"
  ],
  [
    "time-functions/src/minutestohours.js~minutestohours",
    "function/index.html#static-function-minutesToHours",
    "<span>minutesToHours</span> <span class=\"search-result-import-path\">time-functions/src/minutesToHours.js</span>",
    "function"
  ],
  [
    "time-functions/src/minutestoseconds.js~minutestoseconds",
    "function/index.html#static-function-minutesToSeconds",
    "<span>minutesToSeconds</span> <span class=\"search-result-import-path\">time-functions/src/minutesToSeconds.js</span>",
    "function"
  ],
  [
    "time-functions/src/normalizecycledmilliseconds.js~normalizecycledmilliseconds",
    "function/index.html#static-function-normalizeCycledMilliseconds",
    "<span>normalizeCycledMilliseconds</span> <span class=\"search-result-import-path\">time-functions/src/normalizeCycledMilliseconds.js</span>",
    "function"
  ],
  [
    "time-functions/src/parsemillisecondstotime.js~parsemillisecondstotime",
    "function/index.html#static-function-parseMillisecondsToTime",
    "<span>parseMillisecondsToTime</span> <span class=\"search-result-import-path\">time-functions/src/parseMillisecondsToTime.js</span>",
    "function"
  ],
  [
    "time-functions/src/secondstomilliseconds.js~secondstomilliseconds",
    "function/index.html#static-function-secondsToMilliseconds",
    "<span>secondsToMilliseconds</span> <span class=\"search-result-import-path\">time-functions/src/secondsToMilliseconds.js</span>",
    "function"
  ],
  [
    "time-functions/src/secondstominutes.js~secondstominutes",
    "function/index.html#static-function-secondsToMinutes",
    "<span>secondsToMinutes</span> <span class=\"search-result-import-path\">time-functions/src/secondsToMinutes.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/__tests__/hourstominutes.js",
    "file/src/__tests__/hoursToMinutes.js.html",
    "src/__tests__/hoursToMinutes.js",
    "file"
  ],
  [
    "src/__tests__/millisecondstoseconds.js",
    "file/src/__tests__/millisecondsToSeconds.js.html",
    "src/__tests__/millisecondsToSeconds.js",
    "file"
  ],
  [
    "src/__tests__/minutestohours.js",
    "file/src/__tests__/minutesToHours.js.html",
    "src/__tests__/minutesToHours.js",
    "file"
  ],
  [
    "src/__tests__/minutestoseconds.js",
    "file/src/__tests__/minutesToSeconds.js.html",
    "src/__tests__/minutesToSeconds.js",
    "file"
  ],
  [
    "src/__tests__/normalizecycledmilliseconds.js",
    "file/src/__tests__/normalizeCycledMilliseconds.js.html",
    "src/__tests__/normalizeCycledMilliseconds.js",
    "file"
  ],
  [
    "src/__tests__/parsemillisecondstotime.js",
    "file/src/__tests__/parseMillisecondsToTime.js.html",
    "src/__tests__/parseMillisecondsToTime.js",
    "file"
  ],
  [
    "src/__tests__/secondstomilliseconds.js",
    "file/src/__tests__/secondsToMilliseconds.js.html",
    "src/__tests__/secondsToMilliseconds.js",
    "file"
  ],
  [
    "src/__tests__/secondstominutes.js",
    "file/src/__tests__/secondsToMinutes.js.html",
    "src/__tests__/secondsToMinutes.js",
    "file"
  ],
  [
    "src/constants.js",
    "file/src/constants.js.html",
    "src/constants.js",
    "file"
  ],
  [
    "src/hourstominutes.js",
    "file/src/hoursToMinutes.js.html",
    "src/hoursToMinutes.js",
    "file"
  ],
  [
    "src/millisecondstoseconds.js",
    "file/src/millisecondsToSeconds.js.html",
    "src/millisecondsToSeconds.js",
    "file"
  ],
  [
    "src/minutestohours.js",
    "file/src/minutesToHours.js.html",
    "src/minutesToHours.js",
    "file"
  ],
  [
    "src/minutestoseconds.js",
    "file/src/minutesToSeconds.js.html",
    "src/minutesToSeconds.js",
    "file"
  ],
  [
    "src/normalizecycledmilliseconds.js",
    "file/src/normalizeCycledMilliseconds.js.html",
    "src/normalizeCycledMilliseconds.js",
    "file"
  ],
  [
    "src/parsemillisecondstotime.js",
    "file/src/parseMillisecondsToTime.js.html",
    "src/parseMillisecondsToTime.js",
    "file"
  ],
  [
    "src/secondstomilliseconds.js",
    "file/src/secondsToMilliseconds.js.html",
    "src/secondsToMilliseconds.js",
    "file"
  ],
  [
    "src/secondstominutes.js",
    "file/src/secondsToMinutes.js.html",
    "src/secondsToMinutes.js",
    "file"
  ]
]