const MILLISECONDS_IN_ONE_SECOND = 1000;
const SECONDS_IN_ONE_MINUTE = 60;
const MINUTES_IN_ONE_HOUR = 60;
const HOURS_IN_ONE_DAY = 24;

export {
  MILLISECONDS_IN_ONE_SECOND,
  SECONDS_IN_ONE_MINUTE,
  MINUTES_IN_ONE_HOUR,
  HOURS_IN_ONE_DAY
};
